# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Serialize R data using a JSON type string
#'
#' @param x R data of (nearly) any type
#' @param schema JSON type string
#' @export
mlc_serialize <- function(x, schema) {
    .Call('_rmorlocinternals_mlc_serialize', PACKAGE = 'rmorlocinternals', x, schema)
}

#' Deserialize JSON data to an R native type using a JSON type string
#'
#' @param data JSON data
#' @param schema JSON type string
mlc_deserialize_ <- function(data, schema) {
    .Call('_rmorlocinternals_mlc_deserialize_', PACKAGE = 'rmorlocinternals', data, schema)
}

